// <auto-generated />
using System;
using FinancingLead.Infrastructure.Dbcontext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinancingLead.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinancingLead.Domain.Entities.FinancingLead", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ReviewReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ReviewStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("RowVersion");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_FinancingLeads_CreatedAt");

                    b.HasIndex("ReviewStatus")
                        .HasDatabaseName("IX_FinancingLeads_ReviewStatus");

                    b.HasIndex("CreatedAt", "ReviewStatus")
                        .IsDescending(true, false)
                        .HasDatabaseName("IX_FinancingLeads_CreatedAt_ReviewStatus");

                    b.ToTable("FinancingLeads", (string)null);
                });

            modelBuilder.Entity("FinancingLead.Domain.Entities.FinancingLead", b =>
                {
                    b.OwnsOne("FinancingLead.Domain.ValueObjects.BusinessInformation", "Business", b1 =>
                        {
                            b1.Property<Guid>("FinancingLeadId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal?>("AnnualIncome")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<int>("CommercialRegisterType")
                                .HasColumnType("int");

                            b1.Property<string>("TypeOfActivity")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.HasKey("FinancingLeadId");

                            b1.ToTable("FinancingLeads");

                            b1.WithOwner()
                                .HasForeignKey("FinancingLeadId");
                        });

                    b.OwnsOne("FinancingLead.Domain.ValueObjects.ContactInformation", "Contact", b1 =>
                        {
                            b1.Property<Guid>("FinancingLeadId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(254)
                                .HasColumnType("nvarchar(254)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("PhoneE164")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("nvarchar(16)");

                            b1.Property<int?>("PreferredContactMethod")
                                .HasColumnType("int");

                            b1.HasKey("FinancingLeadId");

                            b1.HasIndex("Email")
                                .HasDatabaseName("IX_FinancingLeads_Contact_Email");

                            b1.HasIndex("PhoneE164")
                                .HasDatabaseName("IX_FinancingLeads_Contact_PhoneE164");

                            b1.ToTable("FinancingLeads");

                            b1.WithOwner()
                                .HasForeignKey("FinancingLeadId");
                        });

                    b.Navigation("Business")
                        .IsRequired();

                    b.Navigation("Contact")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
